In [390]:
import numpy as np
import scipy
import pandas as pd
import math
import random
import sklearn
from scipy.sparse import csr_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse.linalg import svds
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from pymongo import MongoClient

In [13]:
user_oldfile = pd.read_csv('data/datalist.csv')
infomations = pd.read_csv('data/infomations_store.csv',index_col=0)
response = pd.read_csv('data/Form.csv',index_col=0)

In [35]:
user_interactions = user_oldfile.iloc[0:,[6,0,2,3]]

In [42]:
user_interactions[user_interactions['User_ID'] == 35]

      User_ID  Store_ID       User  Rating
1          35         0  vanai sun       3
850        35         6  vanai sun       4
1006       35         7  vanai sun       4

In [22]:
store = store.drop_duplicates()

In [27]:
user_interactions.head()

   Store_ID                        User  Rating
0         0                   Nuunet D.       5
1         0                   vanai sun       3
2         0              Phonanan Seeon       5
3         0  Chavakorn Laophetsakunchai       5
4         0               community man       5

In [180]:
users_items_pivot_matrix_df = user_interactions.pivot_table(index="User_ID",columns="Store_ID",values='Rating').fillna(0)

In [181]:
users_items_pivot_matrix = users_items_pivot_matrix_df.values

In [182]:
users_items_pivot_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [3., 0., 0., ..., 0., 0., 0.],
       [5., 0., 5., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 5.],
       [0., 0., 0., ..., 0., 0., 5.],
       [0., 0., 0., ..., 0., 0., 5.]])

In [137]:
users_ids = list(users_items_pivot_matrix_df.index)

In [138]:
users_ids[0:10]

[34, 35, 36, 37, 38, 39, 40, 41, 42, 43]

In [56]:
users_items_pivot_sparse_matrix = csr_matrix(users_items_pivot_matrix)
users_items_pivot_sparse_matrix

<2264x34 sparse matrix of type '<class 'numpy.float64'>'
	with 3209 stored elements in Compressed Sparse Row format>

In [61]:
#The number of factors to factor the user-item matrix.
NUMBER_OF_FACTORS_MF = 15
#Performs matrix factorization of the original user item matrix
#U, sigma, Vt = svds(users_items_pivot_matrix, k = NUMBER_OF_FACTORS_MF)
U, sigma, Vt = svds(users_items_pivot_sparse_matrix, k = NUMBER_OF_FACTORS_MF)

In [62]:
U.shape

(2264, 15)

In [63]:
Vt.shape

(15, 34)

In [64]:
sigma = np.diag(sigma)
sigma.shape

(15, 15)

In [65]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) 
all_user_predicted_ratings

array([[ 4.97719807e+00,  2.56110902e-01,  8.55451668e-02, ...,
         3.66238778e-02, -2.11614965e-03, -7.93803107e-03],
       [ 2.98391296e+00,  9.59150353e-02,  2.52521566e-02, ...,
         1.67009856e-01, -1.20679790e-03, -4.77645912e-02],
       [ 4.95734769e+00,  1.25532105e+00,  1.35953498e+00, ...,
         1.05131326e+00, -2.78836053e-02,  2.47403770e-01],
       ...,
       [-7.93803107e-03,  5.83350992e-02,  6.35243121e-02, ...,
        -1.26380236e-02, -2.62659715e-02,  1.34903574e-01],
       [-7.93803107e-03,  5.83350992e-02,  6.35243121e-02, ...,
        -1.26380236e-02, -2.62659715e-02,  1.34903574e-01],
       [-7.93803107e-03,  5.83350992e-02,  6.35243121e-02, ...,
        -1.26380236e-02, -2.62659715e-02,  1.34903574e-01]])

In [66]:
all_user_predicted_ratings_norm = (all_user_predicted_ratings - all_user_predicted_ratings.min()) / (all_user_predicted_ratings.max() - all_user_predicted_ratings.min())

In [67]:
cf_preds_df = pd.DataFrame(all_user_predicted_ratings_norm, columns = users_items_pivot_matrix_df.columns, index=users_ids).transpose()
cf_preds_df.head(10)

,34,35,36,37,38,39,40,41,42,43,...,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297
Store_ID,,,,,,,,,,,,,,,,,,,,,
0,0.787015,0.521717,0.784373,0.839000,0.781878,0.816042,0.787015,0.680130,0.654526,0.818313,...,0.123513,0.123513,0.123513,0.123513,0.123724,0.123513,0.123513,0.123513,0.123513,0.123513
1,0.158657,0.137335,0.291648,0.259740,0.188589,0.242184,0.158657,0.344038,0.151839,0.223502,...,0.132334,0.132334,0.132334,0.132334,0.130781,0.132334,0.132334,0.132334,0.132334,0.132334
2,0.135955,0.127930,0.305518,0.242279,0.186202,0.196646,0.135955,0.327005,0.133678,0.194768,...,0.133024,0.133024,0.133024,0.133024,0.131333,0.133024,0.133024,0.133024,0.133024,0.133024
3,0.124427,0.122382,0.107287,0.137324,0.113862,0.650373,0.124427,0.109133,0.124455,0.779130,...,0.136599,0.136599,0.136599,0.136599,0.134193,0.136599,0.136599,0.136599,0.136599,0.136599
4,0.119432,0.104258,0.676567,0.361834,0.690634,0.171284,0.119432,0.121950,0.120459,0.086490,...,0.173964,0.173964,0.173964,0.173964,0.164085,0.173964,0.173964,0.173964,0.173964,0.173964
5,0.122379,0.118870,0.101591,0.150329,0.109284,0.138387,0.122379,0.153013,0.122817,0.144337,...,0.130587,0.130587,0.130587,0.130587,0.129383,0.130587,0.130587,0.130587,0.130587,0.130587
6,0.124374,0.652771,0.107232,0.142203,0.114718,0.652096,0.124374,0.651724,0.124413,0.120179,...,0.119639,0.119639,0.119639,0.119639,0.120625,0.119639,0.119639,0.119639,0.119639,0.119639
7,0.124364,0.651775,0.635115,0.129520,0.112484,0.122593,0.124364,0.129015,0.124405,0.115697,...,0.122345,0.122345,0.122345,0.122345,0.122790,0.122345,0.122345,0.122345,0.122345,0.122345
8,0.134621,0.131764,0.223637,0.195053,0.171830,0.182478,0.134621,0.226822,0.132610,0.192446,...,0.132756,0.132756,0.132756,0.132756,0.131119,0.132756,0.132756,0.132756,0.132756,0.132756
9,0.134693,0.128726,0.170859,0.162592,0.145215,0.153973,0.134693,0.178522,0.132668,0.163145,...,0.128088,0.128088,0.128088,0.128088,0.127384,0.128088,0.128088,0.128088,0.128088,0.128088

In [68]:
len(cf_preds_df.columns)

2264

In [244]:
def recommendations(user_id, user_item_matrix, num_recommendations,num_components):
    # Perform SVD on the user-item matrix
    U, sigma, Vt = svds(user_item_matrix, k = num_components)
    
    
    # Get the user's row from the U matrix
    user_row = U[user_id, :]

    
    # Get the dot product of the user row and the Vt matrix
    recommendations = user_row.dot(Vt)
    
    
    # Sort the recommendations in descending order
    recommendations = recommendations.argsort()[::-1]
    
    
    # Return the top num_recommendations recommendations
    return recommendations[:num_recommendations]

In [246]:
recommendations(4,users_items_pivot_matrix,10,10)

TypeError: type not understood

In [291]:
donors_projects_pivot_matrix = users_items_pivot_matrix_df.values

# Get donor ids
donors_ids = list(users_items_pivot_matrix_df.index)

# Print the first 5 rows of the donor-project matrix
donors_projects_pivot_matrix[:5]

array([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [3., 0., 0., 0., 0., 0., 4., 4., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [5., 0., 5., 0., 5., 0., 0., 4., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [5., 5., 4., 0., 0., 0., 0., 0., 0., 0., 5., 0., 0., 0., 0., 3.,
        0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 4., 0., 0., 0., 0., 0.,
        0., 0.],
       [5., 0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [293]:
U, sigma, Vt = svds(donors_projects_pivot_matrix, k = 20)
sigma = np.diag(sigma)

# Reconstruct the matrix by multiplying its factors
all_donor_predicted_ratings = np.dot(np.dot(U, sigma), Vt) 

#Converting the reconstructed matrix back to a Pandas dataframe
cf_preds_df = pd.DataFrame(all_donor_predicted_ratings, 
                           columns = users_items_pivot_matrix_df.columns, 
                           index=donors_ids).transpose()
cf_preds_df.head()

,34,35,36,37,38,39,40,41,42,43,...,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297
Store_ID,,,,,,,,,,,,,,,,,,,,,
0,4.993630,2.997033,4.988051,4.996424,4.994376,4.979313,4.993630,4.025239,3.994904,5.055905,...,-0.048956,-0.048956,-0.048956,-0.048956,-0.039165,-0.048956,-0.048956,-0.048956,-0.048956,-0.048956
1,0.050246,0.067190,1.203011,5.510478,-0.042714,4.179446,0.050246,3.549468,0.040197,3.173682,...,0.871590,0.871590,0.871590,0.871590,0.697272,0.871590,0.871590,0.871590,0.871590,0.871590
2,-0.001422,-0.027508,1.185550,3.549053,0.095548,1.985604,-0.001422,1.924972,-0.001137,1.214473,...,-0.043735,-0.043735,-0.043735,-0.043735,-0.034988,-0.043735,-0.043735,-0.043735,-0.043735,-0.043735
3,-0.001596,-0.004504,-0.039991,-0.025013,-0.009001,3.999684,-0.001596,-0.007075,-0.001277,5.009749,...,-0.027242,-0.027242,-0.027242,-0.027242,-0.021793,-0.027242,-0.027242,-0.027242,-0.027242,-0.027242
4,0.000746,-0.032267,4.906053,0.037259,4.903136,0.142251,0.000746,0.028316,0.000597,-0.131862,...,-0.151245,-0.151245,-0.151245,-0.151245,-0.120996,-0.151245,-0.151245,-0.151245,-0.151245,-0.151245

In [381]:
class CFRecommender:
    
    MODEL_NAME = 'Collaborative Filtering'
    
    def __init__(self, cf_predictions_df, projects_df=None):
        self.cf_predictions_df = cf_predictions_df
        self.projects_df = projects_df
        
    def get_model_name(self):
        return self.MODEL_NAME
        
    def recommend_projects(self, donor_id, projects_to_ignore=[], topn=10):
        # Get and sort the donor's predictions
        sorted_donor_predictions = self.cf_predictions_df[donor_id].sort_values(ascending=False) \
                                    .reset_index().rename(columns={donor_id: 'recStrength'})
        
        # Recommend the highest predicted projects that the donor hasn't donated to
        recommendations_df = sorted_donor_predictions[~sorted_donor_predictions['Store_ID'].isin(projects_to_ignore)] \
                               .sort_values('recStrength', ascending = False) \
                               .head(topn)
        
 
        recommendations_df = recommendations_df.merge(self.projects_df, how = 'left', 
                                                          left_on = 'Store_ID', 
                                                          right_on = 'Store_ID')[['Store_ID','Store','recStrength']]

        return recommendations_df

In [388]:
cfr_model = CFRecommender(cf_preds_df, store)
test =  cfr_model.recommend_projects(36)

In [389]:
test

   Store_ID                     Store  recStrength
0        19        Impression Sunrise     5.087569
1         0   NAP's Coffee & Roasters     4.988051
2         4               Nap x Warin     4.906053
3         7               ROOF COFFEE     3.934173
4        10                    Amarna     1.339977
5         1                    sangob     1.203011
6         2                  SongSarn     1.185550
7        11                 Attaroast     0.724430
8         8  11.11 Gallery and Coffee     0.565426
9        24                 REDCOFFEE     0.499554

In [401]:
client = MongoClient('localhost', 27017)
db = client['Infomations']
users_collection = db['Transaction_user']

In [419]:
data = users_collection.find({}, {'Store':1, '_id':0,'User':1,'Rating':1})
df11 =  pd.DataFrame(list(data))

In [422]:
df11

                        Store                        User  Rating
0     NAP's Coffee & Roasters                   Nuunet D.       5
1     NAP's Coffee & Roasters                   vanai sun       3
2     NAP's Coffee & Roasters              Phonanan Seeon       5
3     NAP's Coffee & Roasters  Chavakorn Laophetsakunchai       5
4     NAP's Coffee & Roasters               community man       5
...                       ...                         ...     ...
3286             Yuanjai Cafe          อาจณรงค์ กลมเกลียว       5
3287             Yuanjai Cafe                          은하       5
3288             Yuanjai Cafe              ประจงจิต จันทป       5
3289             Yuanjai Cafe          Chatthawat Warnjai       5
3290             Yuanjai Cafe                 TAE.SIRIWAT       5

[3291 rows x 3 columns]

In [424]:
user_df = df11.pivot_table(index="User",columns="Store",values='Rating').fillna(0)

In [425]:
user_df

Store,11.11 Gallery and Coffee,Abe Specialty Coffee,Amarna,Anna Roasters,Attaroast,BaanHuakham Cafe & Farmstay,BalconyKiss Coffee,Blendstorm Coffee Roasters,Blues Coffee,Bossa cafe,...,ROSIEHOLM,Rogue Roasters,Saereesook,Snoopcat Cafe,SongSarn,Stufe coffee,Tree Cafe Rim Moon,Yuanjai Cafe,r o u n d,sangob
User,,,,,,,,,,,,,,,,,,,,,
01 มติมนต์ จํานงค์,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
113_kammika raksa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1904x,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984whatthehell,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
212ปาณิตตา ศิริชัย,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
蔡賢德Karanpon,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
김주일,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
남궁진영,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
박선아,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
은하,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0

In [453]:
user_martix_df_values = user_df.values
user_ids = list(user_df.index)

In [435]:
user_martix_df_values.shape

(2237, 33)

In [455]:
import pickle

In [456]:
U, sigma, Vt = svds(user_martix_df_values, k = 15)
sigma = np.diag(sigma)

# Reconstruct the matrix by multiplying its factors
predicted_ratings = np.dot(np.dot(U, sigma), Vt) 

#Converting the reconstructed matrix back to a Pandas dataframe
preds_df = pd.DataFrame(predicted_ratings, 
                           columns = user_df.columns, 
                           index=user_ids).transpose()
with open('preds_df.pkl', 'wb') as f:
    pickle.dump(preds_df, f)

In [457]:
with open('preds_df.pkl', 'rb') as f:
     preds_df_1 = pickle.load(f)

In [471]:
class CFRecommender2:
    
    MODEL_NAME = 'Collaborative Filtering'
    
    def __init__(self, cf_predictions_df, projects_df=None):
        self.cf_predictions_df = cf_predictions_df
        self.projects_df = projects_df
        
    def get_model_name(self):
        return self.MODEL_NAME
        
    def recommend_projects(self, donor_id, projects_to_ignore=[], topn=33):
        # Get and sort the donor's predictions
        sorted_donor_predictions = self.cf_predictions_df[donor_id].sort_values(ascending=False) \
                                    .reset_index().rename(columns={donor_id: 'recStrength'})
        
        # Recommend the highest predicted projects that the donor hasn't donated to
        recommendations_df = sorted_donor_predictions[~sorted_donor_predictions['Store'].isin(projects_to_ignore)] \
                               .sort_values('recStrength', ascending = False) \
                               .head(topn)
        


        return recommendations_df

In [472]:
hh = CFRecommender2(preds_df_1,user_df)

In [489]:
gg = hh.recommend_projects('01 มติมนต์ จํานงค์',['Tree Cafe Rim Moon'])

In [542]:
non_zero_cols = user_df.columns[(user_df != 0).any()]

In [548]:
user_df

Store,11.11 Gallery and Coffee,Abe Specialty Coffee,Amarna,Anna Roasters,Attaroast,BaanHuakham Cafe & Farmstay,BalconyKiss Coffee,Blendstorm Coffee Roasters,Blues Coffee,Bossa cafe,...,ROSIEHOLM,Rogue Roasters,Saereesook,Snoopcat Cafe,SongSarn,Stufe coffee,Tree Cafe Rim Moon,Yuanjai Cafe,r o u n d,sangob
User,,,,,,,,,,,,,,,,,,,,,
01 มติมนต์ จํานงค์,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
113_kammika raksa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1904x,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984whatthehell,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
212ปาณิตตา ศิริชัย,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
蔡賢德Karanpon,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
김주일,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
남궁진영,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
박선아,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
은하,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0

In [561]:
liked_items = user_df[user_df.index == User].nonzero()[1]

NameError: name 'User' is not defined

In [579]:
user_df.loc['01 มติมนต์ จํานงค์'].nonzero()

C:\Users\Note\AppData\Local\Temp\ipykernel_9624\1629966388.py:1: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
  user_df.loc['01 มติมนต์ จํานงค์'][0].nonzero()

(array([], dtype=int64),)

In [ ]:
# user_df[user_df.index == '01 มติมนต์ จํานงค์'].nonzero()[1]

In [522]:
json2 = gg['Store']

In [581]:
# user_df[user_df.index == '01 มติมนต์ จํานงค์'].nonzero()[1]

user_row = user_df.loc[user_df == '01 มติมนต์ จํานงค์']

# Find the items that the user has interacted with
interacted_items = user_row.loc[:, user_row.any()].columns

ValueError: Cannot index with multidimensional key

In [533]:

messs = {
    "data":[x for x in json2]
}

In [534]:
aaa = json.dumps(messs)

In [535]:
parsed = json.loads(aaa)
parsed

{'data': ['sangob',
  'Stufe coffee',
  'LAVA  JAVA Coffee Roasters',
  'PENSER CAFE',
  'Saereesook',
  'Nap x Warin',
  'Attaroast',
  'Blues Coffee',
  'LIFE Roasters',
  'Impression Sunrise',
  'GODFATHER COFFEE',
  'Anna Roasters',
  'Phantae Coffee',
  'ROOF COFFEE',
  'My Papilio',
  'Commune Drink/Talk/Share',
  'Bossa cafe',
  'Snoopcat Cafe',
  'Amarna',
  'r o u n d',
  "NAP's Coffee & Roasters",
  'BalconyKiss Coffee',
  'ROSIEHOLM',
  'Rogue Roasters',
  'Blendstorm Coffee Roasters',
  '11.11 Gallery and Coffee',
  'REDCOFFEE',
  'Yuanjai Cafe',
  'MiND-K coffee and bake',
  'Abe Specialty Coffee',
  'BaanHuakham Cafe & Farmstay',
  'SongSarn']}

In [491]:
a['data'] = json2

In [514]:
json.dumps(messs)

'{"data": {"1": "sangob", "2": "Stufe coffee", "3": "LAVA  JAVA Coffee Roasters", "4": "PENSER CAFE", "5": "Saereesook", "6": "Nap x Warin", "7": "Attaroast", "8": "Blues Coffee", "9": "LIFE Roasters", "10": "Impression Sunrise", "11": "GODFATHER COFFEE", "12": "Anna Roasters", "13": "Phantae Coffee", "14": "ROOF COFFEE", "15": "My Papilio", "16": "Commune Drink/Talk/Share", "17": "Bossa cafe", "18": "Snoopcat Cafe", "19": "Amarna", "20": "r o u n d", "21": "NAP\'s Coffee & Roasters", "22": "BalconyKiss Coffee", "23": "ROSIEHOLM", "24": "Rogue Roasters", "25": "Blendstorm Coffee Roasters", "26": "11.11 Gallery and Coffee", "27": "REDCOFFEE", "28": "Yuanjai Cafe", "29": "MiND-K coffee and bake", "30": "Abe Specialty Coffee", "31": "BaanHuakham Cafe & Farmstay", "32": "SongSarn"}}'

'["sangob", "Stufe coffee", "LAVA  JAVA Coffee Roasters", "PENSER CAFE", "Saereesook", "Nap x Warin", "Attaroast", "Blues Coffee", "LIFE Roasters", "Impression Sunrise", "GODFATHER COFFEE", "Anna Roasters", "Phantae Coffee", "ROOF COFFEE", "My Papilio", "Commune Drink/Talk/Share", "Bossa cafe", "Snoopcat Cafe", "Amarna", "r o u n d", "NAP\'s Coffee & Roasters", "BalconyKiss Coffee", "ROSIEHOLM", "Rogue Roasters", "Blendstorm Coffee Roasters", "11.11 Gallery and Coffee", "REDCOFFEE", "Yuanjai Cafe", "MiND-K coffee and bake", "Abe Specialty Coffee", "BaanHuakham Cafe & Farmstay", "SongSarn"]'

In [536]:
json2 = gg['Store']
messs = {
    "data":[x for x in json2]
}
sb = json.dumps(messs)
s = json.loads(sb)