In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# import data to pandas

In [13]:
df_form = pd.read_csv('../data/Form.csv')

In [14]:
df_form.head()

,Timestamp,Age,Gender,Store,menu,Rating,amenities
0,1/3/2023 16:52:51,20,male,"NAP's Coffee & Roasters, sangob, Nap x Warin, ...",espresso,4,"Free Wi-Fi, Bar on site"
1,1/3/2023 16:59:44,16,female,"BalconyKiss Coffee, ROOF COFFEE, LAVA JAVA Co...",latte,4,"Toilets, Free Wi-Fi, Good for kid"
2,1/3/2023 17:00:34,22,male,"NAP's Coffee & Roasters, SongSarn, Yuanjai Cafe",americano,5,"Free Wi-Fi, High chairs, Bar on site"
3,1/3/2023 17:00:50,21,female,"NAP's Coffee & Roasters, Nap x Warin, Snoopcat...",latte,5,"Toilets, Free Wi-Fi"
4,1/3/2023 17:01:45,19,male,"NAP's Coffee & Roasters, sangob, Nap x Warin, ...",cappuccino,4,"Free Wi-Fi, Good for kid, Bar on site"

In [20]:
df_real = pd.read_csv('./data/infomations_store.csv',index_col=0)

In [22]:
df_real.head()

,store,type,address\t,plus_code,latitude,longitude,amenities,menu coffee,menu non coffee,rating,count_rating
0,NAP's Coffee & Roasters,speedbar,"49, 1 ถนน ศรีณรงค์ ตำบลในเมือง อำเภอเมืองอุบลร...",6VH8+F5 เทศบาลนครอุบลราชธานี อำเภอเมืองอุบลราช...,15.228920,104.865365,Toilets,"hazelnut latte,vanilla latte,caramel latte,esp...","Red Plum Sparking,Honey Lemon Sparking,Lychee ...",4.6,178
1,sangob,speedbar,149 ถนน พรหมเทพ ในเมือง เมือง อุบลราชธานี 34000,6VG5+3Q เทศบาลนครอุบลราชธานี อำเภอเมืองอุบลราช...,15.225389,104.859395,"Free Wi-Fi,Toilets","espresso,americano,cappuccino,mocha,latte,cold...","milk caremel,matcha milk,apple tea,peach tea,c...",4.7,57
2,SongSarn,slowbar,ถ.พรหมเทพ ซอย.ข้างร้านรานี ที่มีStreet Art Mue...,6VG5+4C เทศบาลนครอุบลราชธานี อำเภอเมืองอุบลราช...,15.225416,104.858555,Toilets,"espresso,americano,cappuccino,mocha,latte,cold...","cocoa,matcha,peach tea,vanilla ginger,thai tea...",4.6,52
3,LIFE Roasters,"hybrid,bakery",202/3 ถนนสุริยาตร์ ตำบล ในเมือง อำเภอเมืองอุบล...,6VQ6+3F เทศบาลนครอุบลราชธานี อำเภอเมืองอุบลราช...,15.237538,104.861231,Toilets,"sparkling americano,tonic americano,caramel ma...","Iced cocoa,Iced cocoa mint,Iced matcha latte,I...",4.6,255
4,Nap x Warin,speedbar,16 ถนนเทศบาล 9 ตำบล วารินชำราบ อำเภอวารินชำราบ...,5VR6+8Q ตำบล วารินชำราบ อำเภอวารินชำราบ อุบลรา...,15.190857,104.861934,"Free Wi-Fi,Good for kids,Toilets,Bar on site","Espresso Sparkling Yuzu,Lychee Espresso Tonic,...","Matcha Sparkling Yuzu,Yuzu Black Lemon Tea,Cho...",4.5,87

In [23]:
df_user_review = pd.read_csv('./data/datatest2.csv ')